#!/usr/bin/env python3
"""JANUS P0 preservation integration evidence verifier.

This tool evaluates *already produced* local evidence against the pre-registered
P0 preservation conditions. It does not materialize repositories, replay source
code, execute commands, mutate Git, or generate producer receipts.

The input evidence bundle may contain sensitive local digests. The emitted
summary is deliberately redacted and never includes those local digests, failed
variant IDs, conflict message IDs, checkpoint IDs, source identity digests, or
source pins.

Evidence consistency is not empirical replay. Producer receipts still need to
be generated by their own exact-head harnesses.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path
from typing import Any

BUNDLE_SCHEMA = "janus.nexus.preservation_integration_evidence.v1"
LOCK_SCHEMA = "janus.nexus.preservation_integration_lock.v1"
SUMMARY_SCHEMA = "janus.nexus.preservation_integration_public_summary.v1"
PREREGISTRATION_RECEIPT = "5308388940"
EXPECTED_SOURCE_COUNT = 44
HEX40 = re.compile(r"^[0-9a-f]{40}$")
HEX64 = re.compile(r"^[0-9a-f]{64}$")
REPOSITORY = re.compile(r"^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$")

PRODUCER_KEYS = {
    "materializer",
    "privacy_projection",
    "source_pin_contract",
    "variant_lineage",
    "handoff_ledger",
    "swarm_recovery",
    "source_identity_guard",
}
EXPECTED_PRODUCER_REPOSITORIES = {
    "materializer": "Hawkar-usls/Janus_Genesis",
    "privacy_projection": "Hawkar-usls/Janus_Genesis",
    "source_pin_contract": "Hawkar-usls/Janus_Genesis",
    "variant_lineage": "Hawkar-usls/Janus_Genesis",
    "handoff_ledger": "Hawkar-usls/Janus_Genesis",
    "swarm_recovery": "Hawkar-usls/janus-distributed-ai-swarm",
    "source_identity_guard": "Hawkar-usls/Janus_Genesis",
}
EXPECTED_PRODUCER_PULL_REQUESTS = {
    "materializer": 122,
    "privacy_projection": 125,
    "source_pin_contract": 126,
    "variant_lineage": 123,
    "handoff_ledger": 124,
    "swarm_recovery": 5,
    "source_identity_guard": 133,
}
PRODUCER_REF_KEYS = {"repository", "pull_request", "sha"}

BUNDLE_KEYS = {
    "schema",
    "producer_refs",
    "materializer",
    "source_pins",
    "lineage",
    "handoff",
    "swarm",
    "source_guard",
}

LOCK_KEYS = {
    "schema",
    "preregistration_receipt",
    "expected_source_count",
    "privacy_mode",
    "producer_refs",
}


class PreservationEvidenceError(RuntimeError):
    """Fail-closed evidence admission error."""


def canonical_bytes(value: Any) -> bytes:
    return json.dumps(
        value,
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
        allow_nan=False,
    ).encode("utf-8")


def digest(value: Any) -> str:
    return hashlib.sha256(canonical_bytes(value)).hexdigest()


def _display_keys(values: set[Any]) -> list[str]:
    return sorted(repr(item) for item in values)


def _require_exact_keys(value: Any, expected: set[str], field: str) -> dict[str, Any]:
    if not isinstance(value, dict):
        raise PreservationEvidenceError(f"{field} must be an object")
    keys = set(value)
    if keys != expected:
        missing = _display_keys(expected - keys)
        extra = _display_keys(keys - expected)
        raise PreservationEvidenceError(
            f"{field} keys mismatch; missing={missing}; extra={extra}"
        )
    return value


def _require_sha(value: Any, field: str) -> str:
    if not isinstance(value, str) or not HEX40.fullmatch(value):
        raise PreservationEvidenceError(f"{field} must be exact lowercase 40-hex Git SHA")
    return value


def _require_digest(value: Any, field: str) -> str:
    if not isinstance(value, str) or not HEX64.fullmatch(value):
        raise PreservationEvidenceError(f"{field} must be lowercase 64-hex digest")
    return value


def _require_bool(value: Any, field: str, expected: bool | None = None) -> bool:
    if type(value) is not bool:
        raise PreservationEvidenceError(f"{field} must be boolean")
    if expected is not None and value is not expected:
        raise PreservationEvidenceError(f"{field} must be {expected}")
    return value


def _require_pr_number(value: Any, field: str) -> int:
    if type(value) is not int or value <= 0:
        raise PreservationEvidenceError(f"{field} must be a positive integer PR number")
    return value


def validate_producer_refs(raw: Any, field: str) -> dict[str, dict[str, Any]]:
    value = _require_exact_keys(raw, PRODUCER_KEYS, field)
    cleaned: dict[str, dict[str, Any]] = {}
    for role in sorted(PRODUCER_KEYS):
        ref = _require_exact_keys(value[role], PRODUCER_REF_KEYS, f"{field}.{role}")
        repository = ref.get("repository")
        if not isinstance(repository, str) or not REPOSITORY.fullmatch(repository):
            raise PreservationEvidenceError(
                f"{field}.{role}.repository must be owner/repository identity"
            )
        expected_repository = EXPECTED_PRODUCER_REPOSITORIES[role]
        if repository != expected_repository:
            raise PreservationEvidenceError(
                f"{field}.{role}.repository must be {expected_repository}"
            )
        pull_request = _require_pr_number(
            ref.get("pull_request"), f"{field}.{role}.pull_request"
        )
        expected_pull_request = EXPECTED_PRODUCER_PULL_REQUESTS[role]
        if pull_request != expected_pull_request:
            raise PreservationEvidenceError(
                f"{field}.{role}.pull_request must be canonical producer PR {expected_pull_request}"
            )
        cleaned[role] = {
            "repository": repository,
            "pull_request": pull_request,
            "sha": _require_sha(ref.get("sha"), f"{field}.{role}.sha"),
        }
    return cleaned


def validate_lock(raw: Any) -> dict[str, Any]:
    value = _require_exact_keys(raw, LOCK_KEYS, "lock")
    if value.get("schema") != LOCK_SCHEMA:
        raise PreservationEvidenceError("lock schema mismatch")
    if value.get("preregistration_receipt") != PREREGISTRATION_RECEIPT:
        raise PreservationEvidenceError("lock preregistration receipt mismatch")
    if value.get("expected_source_count") != EXPECTED_SOURCE_COUNT:
        raise PreservationEvidenceError("lock expected source count mismatch")
    if value.get("privacy_mode") != "LOCAL_EVIDENCE_PUBLIC_REDACTED_SUMMARY":
        raise PreservationEvidenceError("lock privacy mode mismatch")
    refs = validate_producer_refs(value.get("producer_refs"), "lock.producer_refs")
    return {
        "schema": LOCK_SCHEMA,
        "preregistration_receipt": PREREGISTRATION_RECEIPT,
        "expected_source_count": EXPECTED_SOURCE_COUNT,
        "privacy_mode": "LOCAL_EVIDENCE_PUBLIC_REDACTED_SUMMARY",
        "producer_refs": refs,
    }


def validate_bundle(raw: Any) -> dict[str, Any]:
    value = _require_exact_keys(raw, BUNDLE_KEYS, "bundle")
    if value.get("schema") != BUNDLE_SCHEMA:
        raise PreservationEvidenceError("bundle schema mismatch")
    refs = validate_producer_refs(value.get("producer_refs"), "bundle.producer_refs")

    materializer = _require_exact_keys(
        value.get("materializer"),
        {
            "source_count",
            "clean_target_rebuild_exercised",
            "rebuild_a_digest",
            "rebuild_b_digest",
            "local_exact_replay_passed",
            "privacy_projection_passed",
            "source_pin_drift",
            "source_writeback_observed",
            "destructive_cleanup_required_for_pass",
        },
        "bundle.materializer",
    )
    if materializer.get("source_count") != EXPECTED_SOURCE_COUNT:
        raise PreservationEvidenceError("materializer source_count must be 44")
    _require_bool(materializer.get("clean_target_rebuild_exercised"), "materializer.clean_target_rebuild_exercised", True)
    rebuild_a = _require_digest(materializer.get("rebuild_a_digest"), "materializer.rebuild_a_digest")
    rebuild_b = _require_digest(materializer.get("rebuild_b_digest"), "materializer.rebuild_b_digest")
    if rebuild_a != rebuild_b:
        raise PreservationEvidenceError("independent materializer rebuild digests differ")
    _require_bool(materializer.get("local_exact_replay_passed"), "materializer.local_exact_replay_passed", True)
    _require_bool(materializer.get("privacy_projection_passed"), "materializer.privacy_projection_passed", True)
    _require_bool(materializer.get("source_pin_drift"), "materializer.source_pin_drift", False)
    _require_bool(materializer.get("source_writeback_observed"), "materializer.source_writeback_observed", False)
    _require_bool(materializer.get("destructive_cleanup_required_for_pass"), "materializer.destructive_cleanup_required_for_pass", False)

    source_pins = _require_exact_keys(
        value.get("source_pins"),
        {
            "typed_pinset_validated",
            "exact_git_replay_required",
            "git_commit_kind",
            "opaque_version_kind",
            "type_inference_used",
            "private_exact_pin_publication",
            "whole_pinset_digest_publication",
        },
        "bundle.source_pins",
    )
    _require_bool(source_pins.get("typed_pinset_validated"), "source_pins.typed_pinset_validated", True)
    _require_bool(source_pins.get("exact_git_replay_required"), "source_pins.exact_git_replay_required", True)
    if source_pins.get("git_commit_kind") != "GIT_COMMIT_SHA1":
        raise PreservationEvidenceError("source_pins.git_commit_kind must be GIT_COMMIT_SHA1")
    if source_pins.get("opaque_version_kind") != "OPAQUE_VERSION_TOKEN":
        raise PreservationEvidenceError("source_pins.opaque_version_kind must be OPAQUE_VERSION_TOKEN")
    _require_bool(source_pins.get("type_inference_used"), "source_pins.type_inference_used", False)
    _require_bool(source_pins.get("private_exact_pin_publication"), "source_pins.private_exact_pin_publication", False)
    _require_bool(source_pins.get("whole_pinset_digest_publication"), "source_pins.whole_pinset_digest_publication", False)

    lineage = _require_exact_keys(
        value.get("lineage"),
        {"expected_head_digest", "observed_head_digest", "failed_variant_ids", "failed_variants_retained"},
        "bundle.lineage",
    )
    expected_lineage = _require_digest(lineage.get("expected_head_digest"), "lineage.expected_head_digest")
    observed_lineage = _require_digest(lineage.get("observed_head_digest"), "lineage.observed_head_digest")
    if expected_lineage != observed_lineage:
        raise PreservationEvidenceError("lineage expected/observed head digest mismatch")
    failed_ids_raw = lineage.get("failed_variant_ids")
    if not isinstance(failed_ids_raw, list) or not failed_ids_raw:
        raise PreservationEvidenceError("lineage requires at least one retained failed variant")
    failed_ids = [
        _require_digest(item, f"lineage.failed_variant_ids[{index}]")
        for index, item in enumerate(failed_ids_raw)
    ]
    if len(failed_ids) != len(set(failed_ids)):
        raise PreservationEvidenceError("lineage failed_variant_ids must be unique")
    _require_bool(lineage.get("failed_variants_retained"), "lineage.failed_variants_retained", True)

    handoff = _require_exact_keys(
        value.get("handoff"),
        {"expected_head_digest", "observed_head_digest", "conflict_message_ids", "conflicts_retained", "reconciliation_status", "majority_vote_used"},
        "bundle.handoff",
    )
    expected_handoff = _require_digest(handoff.get("expected_head_digest"), "handoff.expected_head_digest")
    observed_handoff = _require_digest(handoff.get("observed_head_digest"), "handoff.observed_head_digest")
    if expected_handoff != observed_handoff:
        raise PreservationEvidenceError("handoff expected/observed head digest mismatch")
    conflict_ids_raw = handoff.get("conflict_message_ids")
    if not isinstance(conflict_ids_raw, list) or len(conflict_ids_raw) < 2:
        raise PreservationEvidenceError("handoff requires at least two unique conflict message IDs")
    conflict_ids: list[str] = []
    for index, item in enumerate(conflict_ids_raw):
        if not isinstance(item, str) or not item.strip():
            raise PreservationEvidenceError(f"handoff.conflict_message_ids[{index}] must be a non-empty string")
        conflict_ids.append(item)
    if len(conflict_ids) != len(set(conflict_ids)):
        raise PreservationEvidenceError("handoff requires at least two unique conflict message IDs")
    _require_bool(handoff.get("conflicts_retained"), "handoff.conflicts_retained", True)
    if handoff.get("reconciliation_status") != "HOLD_RECONCILE":
        raise PreservationEvidenceError("handoff reconciliation must be HOLD_RECONCILE")
    _require_bool(handoff.get("majority_vote_used"), "handoff.majority_vote_used", False)

    swarm = _require_exact_keys(
        value.get("swarm"),
        {"checkpoint_digest", "receipt_digest", "session_drop_exercised", "resume_decision", "source_pin_drift", "duplicate_source_mutation_observed"},
        "bundle.swarm",
    )
    _require_digest(swarm.get("checkpoint_digest"), "swarm.checkpoint_digest")
    _require_digest(swarm.get("receipt_digest"), "swarm.receipt_digest")
    _require_bool(swarm.get("session_drop_exercised"), "swarm.session_drop_exercised", True)
    if swarm.get("resume_decision") != "RESUME":
        raise PreservationEvidenceError("swarm resume_decision must be RESUME")
    _require_bool(swarm.get("source_pin_drift"), "swarm.source_pin_drift", False)
    _require_bool(swarm.get("duplicate_source_mutation_observed"), "swarm.duplicate_source_mutation_observed", False)

    source_guard = _require_exact_keys(
        value.get("source_guard"),
        {"before_identity_digest", "after_identity_digest", "writeback_observed", "destructive_effect_observed"},
        "bundle.source_guard",
    )
    before = _require_digest(source_guard.get("before_identity_digest"), "source_guard.before_identity_digest")
    after = _require_digest(source_guard.get("after_identity_digest"), "source_guard.after_identity_digest")
    if before != after:
        raise PreservationEvidenceError("source identity changed across replay")
    _require_bool(source_guard.get("writeback_observed"), "source_guard.writeback_observed", False)
    _require_bool(source_guard.get("destructive_effect_observed"), "source_guard.destructive_effect_observed", False)

    try:
        cleaned = json.loads(canonical_bytes(value).decode("utf-8"))
    except (TypeError, ValueError) as exc:
        raise PreservationEvidenceError(f"bundle is not canonical JSON data: {exc}") from exc
    cleaned["producer_refs"] = refs
    return cleaned


def evaluate(bundle_raw: Any, lock_raw: Any, expected_lock_digest: str) -> dict[str, Any]:
    expected_lock_digest = _require_digest(expected_lock_digest, "expected_lock_digest")
    lock = validate_lock(lock_raw)
    observed_lock_digest = digest(lock)
    if observed_lock_digest != expected_lock_digest:
        raise PreservationEvidenceError("external producer lock digest mismatch")

    bundle = validate_bundle(bundle_raw)
    if bundle["producer_refs"] != lock["producer_refs"]:
        raise PreservationEvidenceError("bundle producer refs do not match external lock")

    summary = {
        "schema": SUMMARY_SCHEMA,
        "decision": "EVIDENCE_BUNDLE_CONSISTENT",
        "preregistration_receipt": PREREGISTRATION_RECEIPT,
        "producer_refs": lock["producer_refs"],
        "producer_lock_digest": observed_lock_digest,
        "source_count": EXPECTED_SOURCE_COUNT,
        "clean_target_rebuild_exercised": True,
        "independent_rebuild_identity_reproduced": True,
        "local_exact_replay_passed": True,
        "privacy_projection_passed": True,
        "typed_source_pin_contract_passed": True,
        "source_pin_type_inference_used": False,
        "private_exact_pin_publication": False,
        "lineage_expected_head_reproduced": True,
        "failed_variant_retention": True,
        "handoff_expected_head_reproduced": True,
        "conflict_retention_and_hold_reconcile": True,
        "swarm_session_drop_recovery": True,
        "source_pin_drift": False,
        "source_writeback_observed": False,
        "destructive_effect_observed": False,
        "destructive_cleanup_required_for_pass": False,
        "majority_vote_used": False,
        "local_sensitive_evidence_persisted_in_summary": False,
        "empirical_replay_claimed_by_this_verifier": False,
        "merge_permission_granted": False,
        "authority_delta": 0,
        "mass_effect_budget_delta": 0,
        "claim_ceiling": (
            "This summary proves only that a supplied local evidence bundle is internally "
            "consistent with an out-of-band-digest-bound producer-reference lock and the "
            "pre-registered P0 conditions. It does not prove that producer harnesses honestly "
            "generated the evidence, that each SHA is a member of the named pull request, "
            "perform repository acquisition, establish an empirical owner-wide replay, or "
            "grant merge/writeback authority."
        ),
    }
    summary["public_summary_digest"] = digest(summary)
    return summary


def _load_json(path: Path, label: str) -> Any:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise PreservationEvidenceError(f"cannot load {label} JSON input") from exc


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--bundle", required=True, type=Path)
    parser.add_argument("--lock", required=True, type=Path)
    parser.add_argument("--expected-lock-digest", required=True)
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        result = evaluate(
            _load_json(args.bundle, "bundle"),
            _load_json(args.lock, "lock"),
            args.expected_lock_digest,
        )
    except PreservationEvidenceError as exc:
        failure = {
            "ok": False,
            "schema": SUMMARY_SCHEMA,
            "error": str(exc),
            "empirical_replay_claimed_by_this_verifier": False,
            "merge_permission_granted": False,
            "authority_delta": 0,
            "mass_effect_budget_delta": 0,
        }
        print(json.dumps(failure, ensure_ascii=False, sort_keys=True), file=sys.stderr)
        return 2
    print(json.dumps(result, ensure_ascii=False, sort_keys=True, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
